on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: kangaechu/hello-world-composite-run-steps-action@v1.0.2
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo rundom-number ${{ steps.foo.outputs.random-number }}
        shell: bash
